// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UEventoBackend.Data;

#nullable disable

namespace UEventoBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260719032932_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UEventoBackend.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anonimo")
                        .HasColumnType("bit");

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estudiante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("UEventoBackend.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "luis.gomez@ug.edu.ec",
                            Nombre = "Luis Gomez",
                            Password = "password123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "marta.sanchez@ug.edu.ec",
                            Nombre = "Marta Sanchez",
                            Password = "password123"
                        });
                });

            modelBuilder.Entity("UEventoBackend.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizadorId")
                        .HasColumnType("int");

                    b.Property<int>("TipoEventoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TipoEventoId");

                    b.ToTable("Eventos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detalles = "Taller práctico sobre la construcción de APIs RESTful.",
                            Fecha = "2026-08-15",
                            Imagen = "",
                            OrganizadorId = 1,
                            TipoEventoId = 2,
                            Titulo = "Introducción a .NET Core"
                        },
                        new
                        {
                            Id = 2,
                            Detalles = "Encuentro anual con múltiples ponencias sobre tecnología.",
                            Fecha = "2026-09-10",
                            Imagen = "",
                            OrganizadorId = 2,
                            TipoEventoId = 4,
                            Titulo = "Congreso de Innovación Tecnológica"
                        });
                });

            modelBuilder.Entity("UEventoBackend.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiereCertificado")
                        .HasColumnType("bit");

                    b.Property<string>("TipoAsistencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Inscripciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cedula = "0912345678",
                            EventoId = 1,
                            Nombre = "Luis Gomez",
                            RequiereCertificado = true,
                            TipoAsistencia = "Presencial"
                        },
                        new
                        {
                            Id = 2,
                            Cedula = "0987654321",
                            EventoId = 1,
                            Nombre = "Marta Sanchez",
                            RequiereCertificado = false,
                            TipoAsistencia = "Virtual"
                        });
                });

            modelBuilder.Entity("UEventoBackend.Models.OrganizadorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Facultad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Organizadores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Cargo = "Docente Titular",
                            Email = "carlos@ug.edu.ec",
                            Facultad = "FCMF",
                            Nombre = "Carlos Mendoza",
                            Password = "1234",
                            Telefono = "0991234567"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Cargo = "Coordinadora de Club",
                            Email = "ana.torres@ug.edu.ec",
                            Facultad = "FING",
                            Nombre = "Ana Torres",
                            Password = "1234",
                            Telefono = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Cargo = "Director Académico",
                            Email = "roberto.silva@ug.edu.ec",
                            Facultad = "FACS",
                            Nombre = "Roberto Silva",
                            Password = "1234",
                            Telefono = "0976543210"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Cargo = "Jefa de Departamento",
                            Email = "maria.lopez@ug.edu.ec",
                            Facultad = "FCMF",
                            Nombre = "María López",
                            Password = "1234",
                            Telefono = "0965432109"
                        },
                        new
                        {
                            Id = 5,
                            Activo = false,
                            Cargo = "Docente Investigador",
                            Email = "juan.perez@ug.edu.ec",
                            Facultad = "FING",
                            Nombre = "Juan Pérez",
                            Password = "1234",
                            Telefono = "0954321098"
                        });
                });

            modelBuilder.Entity("UEventoBackend.Models.PonenteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ponentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biografia = "Experto en machine learning e infraestructuras de datos.",
                            Correo = "alberto.ramos@ug.edu.ec",
                            Especialidad = "Inteligencia Artificial",
                            Institucion = "Universidad de Guayaquil",
                            Nombre = "Dr. Alberto Ramos",
                            Telefono = "0991122334"
                        },
                        new
                        {
                            Id = 2,
                            Biografia = "Auditora de seguridad informática y redes.",
                            Correo = "sofia.castro@ug.edu.ec",
                            Especialidad = "Ciberseguridad",
                            Institucion = "Universidad de Guayaquil",
                            Nombre = "Ing. Sofia Castro",
                            Telefono = "0988877665"
                        });
                });

            modelBuilder.Entity("UEventoBackend.Models.RecursoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 5,
                            Descripcion = "Proyector 4K para auditorios principales.",
                            Disponible = true,
                            Nombre = "Proyector Epson",
                            Tipo = "Audiovisual"
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 10,
                            Descripcion = "Micrófono de solapa y mano con base.",
                            Disponible = true,
                            Nombre = "Micrófono Inalámbrico",
                            Tipo = "Audio"
                        });
                });

            modelBuilder.Entity("UEventoBackend.Models.TipoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposEvento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Conferencia"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Taller"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Seminario"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Congreso"
                        });
                });

            modelBuilder.Entity("UEventoBackend.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@ug.edu.ec",
                            Nombre = "Administrador General",
                            Password = "admin",
                            Tipo = "administrador"
                        });
                });

            modelBuilder.Entity("UEventoBackend.Models.Evento", b =>
                {
                    b.HasOne("UEventoBackend.Models.TipoEvento", "TipoEvento")
                        .WithMany("Eventos")
                        .HasForeignKey("TipoEventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoEvento");
                });

            modelBuilder.Entity("UEventoBackend.Models.Inscripcion", b =>
                {
                    b.HasOne("UEventoBackend.Models.Evento", "Evento")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("UEventoBackend.Models.Evento", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("UEventoBackend.Models.TipoEvento", b =>
                {
                    b.Navigation("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
