// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UEventoBackend.Data;

#nullable disable

namespace UEventoBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UEventoBackend.Models.OrganizadorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Facultad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Organizadores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Cargo = "Docente Titular",
                            Email = "carlos@ug.edu.ec",
                            Facultad = "FCMF",
                            Nombre = "Carlos Mendoza",
                            Password = "1234",
                            Telefono = "0991234567"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Cargo = "Coordinadora de Club",
                            Email = "ana.torres@ug.edu.ec",
                            Facultad = "FING",
                            Nombre = "Ana Torres",
                            Password = "1234",
                            Telefono = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Cargo = "Director Académico",
                            Email = "roberto.silva@ug.edu.ec",
                            Facultad = "FACS",
                            Nombre = "Roberto Silva",
                            Password = "1234",
                            Telefono = "0976543210"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Cargo = "Jefa de Departamento",
                            Email = "maria.lopez@ug.edu.ec",
                            Facultad = "FCMF",
                            Nombre = "María López",
                            Password = "1234",
                            Telefono = "0965432109"
                        },
                        new
                        {
                            Id = 5,
                            Activo = false,
                            Cargo = "Docente Investigador",
                            Email = "juan.perez@ug.edu.ec",
                            Facultad = "FING",
                            Nombre = "Juan Pérez",
                            Password = "1234",
                            Telefono = "0954321098"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
